"""
生成古诗词数据 poetry.js - 小学必备75首
"""
import json

poems = [
    # 一年级
    {"id":1,"title":"咏鹅","author":"骆宾王","dynasty":"唐","grade":"一年级上册",
     "content":[["鹅","鹅","鹅"],["曲项向天歌"],["白毛浮绿水"],["红掌拨清波"]],
     "pinyin":[["é","é","é"],["qū xiàng xiàng tiān gē"],["bái máo fú lǜ shuǐ"],["hóng zhǎng bō qīng bō"]],
     "annotation":"咏：赞美。曲项：弯着脖子。拨：划动。",
     "translation":"鹅，鹅，鹅，弯着脖子朝天唱歌。白色的羽毛浮在绿色的水上，红色的脚掌划动着清澈的水波。"},
    {"id":2,"title":"春晓","author":"孟浩然","dynasty":"唐","grade":"一年级下册",
     "content":[["春眠不觉晓"],["处处闻啼鸟"],["夜来风雨声"],["花落知多少"]],
     "pinyin":[["chūn mián bù jué xiǎo"],["chù chù wén tí niǎo"],["yè lái fēng yǔ shēng"],["huā luò zhī duō shǎo"]],
     "annotation":"眠：睡觉。晓：天亮。闻：听到。",
     "translation":"春天睡觉醒来天已亮了，到处听到鸟的叫声。昨夜的风雨声，不知道花落了多少。"},
    {"id":3,"title":"静夜思","author":"李白","dynasty":"唐","grade":"一年级下册",
     "content":[["床前明月光"],["疑是地上霜"],["举头望明月"],["低头思故乡"]],
     "pinyin":[["chuáng qián míng yuè guāng"],["yí shì dì shàng shuāng"],["jǔ tóu wàng míng yuè"],["dī tóu sī gù xiāng"]],
     "annotation":"疑：好像。举头：抬头。",
     "translation":"床前洒满明亮的月光，好像是地上的霜。抬头望着天上的明月，低头想起了远方的家乡。"},
    {"id":4,"title":"画","author":"王维","dynasty":"唐","grade":"一年级上册",
     "content":[["远看山有色"],["近听水无声"],["春去花还在"],["人来鸟不惊"]],
     "pinyin":[["yuǎn kàn shān yǒu sè"],["jìn tīng shuǐ wú shēng"],["chūn qù huā hái zài"],["rén lái niǎo bù jīng"]],
     "annotation":"这是一首谜语诗，谜底就是题目——画。",
     "translation":"远远看去山有颜色，走近听水却没有声音。春天过去了花还在，人走近了鸟也不害怕。"},
    {"id":5,"title":"悯农（其一）","author":"李绅","dynasty":"唐","grade":"一年级上册",
     "content":[["锄禾日当午"],["汗滴禾下土"],["谁知盘中餐"],["粒粒皆辛苦"]],
     "pinyin":[["chú hé rì dāng wǔ"],["hàn dī hé xià tǔ"],["shuí zhī pán zhōng cān"],["lì lì jiē xīn kǔ"]],
     "annotation":"悯：同情。锄禾：给庄稼松土除草。餐：饭食。",
     "translation":"中午太阳火辣辣地照着，农民还在田里除草，汗水滴在泥土里。谁知道盘中的米饭，每一粒都是辛苦得来的。"},
    {"id":6,"title":"登鹳雀楼","author":"王之涣","dynasty":"唐","grade":"二年级上册",
     "content":[["白日依山尽"],["黄河入海流"],["欲穷千里目"],["更上一层楼"]],
     "pinyin":[["bái rì yī shān jìn"],["huáng hé rù hǎi liú"],["yù qióng qiān lǐ mù"],["gèng shàng yī céng lóu"]],
     "annotation":"鹳雀楼：在山西。依：靠着。穷：尽。",
     "translation":"太阳靠着山边落下了，黄河水向着大海奔流。要想看到更远的景色，就要再登上一层楼。"},
    {"id":7,"title":"望庐山瀑布","author":"李白","dynasty":"唐","grade":"二年级上册",
     "content":[["日照香炉生紫烟"],["遥看瀑布挂前川"],["飞流直下三千尺"],["疑是银河落九天"]],
     "pinyin":[["rì zhào xiāng lú shēng zǐ yān"],["yáo kàn pù bù guà qián chuān"],["fēi liú zhí xià sān qiān chǐ"],["yí shì yín hé luò jiǔ tiān"]],
     "annotation":"香炉：香炉峰。九天：天的最高处。",
     "translation":"阳光照着香炉峰升起紫色烟雾，远远看去瀑布像挂在山前。飞流直下三千尺，让人怀疑是银河从天上落下来了。"},
    {"id":8,"title":"赠汪伦","author":"李白","dynasty":"唐","grade":"二年级上册",
     "content":[["李白乘舟将欲行"],["忽闻岸上踏歌声"],["桃花潭水深千尺"],["不及汪伦送我情"]],
     "pinyin":[["lǐ bái chéng zhōu jiāng yù xíng"],["hū wén àn shàng tà gē shēng"],["táo huā tán shuǐ shēn qiān chǐ"],["bù jí wāng lún sòng wǒ qíng"]],
     "annotation":"踏歌：一边唱歌一边用脚打拍子。不及：比不上。",
     "translation":"我乘船将要出发，忽然听到岸上传来踏歌声。桃花潭的水再深，也比不上汪伦对我的情谊。"},
    {"id":9,"title":"草","author":"白居易","dynasty":"唐","grade":"二年级下册",
     "content":[["离离原上草"],["一岁一枯荣"],["野火烧不尽"],["春风吹又生"]],
     "pinyin":[["lí lí yuán shàng cǎo"],["yī suì yī kū róng"],["yě huǒ shāo bù jìn"],["chūn fēng chuī yòu shēng"]],
     "annotation":"离离：茂盛的样子。枯荣：枯萎和茂盛。",
     "translation":"原野上的草长得很茂盛，每年枯萎后又茂盛地长出来。野火也烧不完，春风一吹又长出来了。"},
    {"id":10,"title":"宿新市徐公店","author":"杨万里","dynasty":"宋","grade":"二年级下册",
     "content":[["篱落疏疏一径深"],["树头花落未成阴"],["儿童急走追黄蝶"],["飞入菜花无处寻"]],
     "pinyin":[["lí luò shū shū yī jìng shēn"],["shù tóu huā luò wèi chéng yīn"],["ér tóng jí zǒu zhuī huáng dié"],["fēi rù cài huā wú chù xún"]],
     "annotation":"篱落：篱笆。径：小路。",
     "translation":"篱笆稀稀疏疏，小路伸向远方。树上的花落了，叶子还没长成树荫。小孩子跑着追黄蝴蝶，可蝴蝶飞进菜花里找不到了。"},
    # 三年级
    {"id":11,"title":"望天门山","author":"李白","dynasty":"唐","grade":"三年级上册",
     "content":[["天门中断楚江开"],["碧水东流至此回"],["两岸青山相对出"],["孤帆一片日边来"]],
     "pinyin":[["tiān mén zhōng duàn chǔ jiāng kāi"],["bì shuǐ dōng liú zhì cǐ huí"],["liǎng àn qīng shān xiāng duì chū"],["gū fān yī piàn rì biān lái"]],
     "annotation":"天门山在安徽。楚江指长江的一段。",
     "translation":"天门山被长江从中间劈开，碧绿的江水向东流到这里又回旋。两岸的青山相对而立，一只小船从太阳那边驶来。"},
    {"id":12,"title":"饮湖上初晴后雨","author":"苏轼","dynasty":"宋","grade":"三年级上册",
     "content":[["水光潋滟晴方好"],["山色空蒙雨亦奇"],["欲把西湖比西子"],["淡妆浓抹总相宜"]],
     "pinyin":[["shuǐ guāng liàn yàn qíng fāng hǎo"],["shān sè kōng méng yǔ yì qí"],["yù bǎ xī hú bǐ xī zǐ"],["dàn zhuāng nóng mǒ zǒng xiāng yí"]],
     "annotation":"潋滟：水波荡漾。西子：西施。",
     "translation":"晴天西湖波光粼粼真美，雨天山色朦胧也很奇妙。如果把西湖比作西施，淡妆浓妆都好看。"},
    {"id":13,"title":"夜书所见","author":"叶绍翁","dynasty":"宋","grade":"三年级上册",
     "content":[["萧萧梧叶送寒声"],["江上秋风动客情"],["知有儿童挑促织"],["夜深篱落一灯明"]],
     "pinyin":[["xiāo xiāo wú yè sòng hán shēng"],["jiāng shàng qiū fēng dòng kè qíng"],["zhī yǒu ér tóng tiāo cù zhī"],["yè shēn lí luò yī dēng míng"]],
     "annotation":"挑促织：捉蟋蟀。篱落：篱笆。",
     "translation":"梧桐叶沙沙响送来了寒意，江上的秋风吹动了旅人的愁思。知道有孩子在捉蟋蟀，夜深了篱笆边还有一盏灯亮着。"},
    {"id":14,"title":"九月九日忆山东兄弟","author":"王维","dynasty":"唐","grade":"三年级下册",
     "content":[["独在异乡为异客"],["每逢佳节倍思亲"],["遥知兄弟登高处"],["遍插茱萸少一人"]],
     "pinyin":[["dú zài yì xiāng wéi yì kè"],["měi féng jiā jié bèi sī qīn"],["yáo zhī xiōng dì dēng gāo chù"],["biàn chā zhū yú shǎo yī rén"]],
     "annotation":"异乡：外乡。茱萸：一种植物，重阳节佩戴。",
     "translation":"独自一人在他乡做客，每到节日更加想念亲人。想到兄弟们重阳登高时，都插着茱萸少了我一个。"},
    {"id":15,"title":"元日","author":"王安石","dynasty":"宋","grade":"三年级下册",
     "content":[["爆竹声中一岁除"],["春风送暖入屠苏"],["千门万户曈曈日"],["总把新桃换旧符"]],
     "pinyin":[["bào zhú shēng zhōng yī suì chú"],["chūn fēng sòng nuǎn rù tú sū"],["qiān mén wàn hù tóng tóng rì"],["zǒng bǎ xīn táo huàn jiù fú"]],
     "annotation":"屠苏：一种酒。曈曈：太阳初升的样子。桃符：春联。",
     "translation":"在爆竹声中旧的一年过去了，春风把温暖送进了屠苏酒。千家万户都沐浴在初升的阳光下，都把旧桃符换成了新的。"},
    {"id":16,"title":"题西林壁","author":"苏轼","dynasty":"宋","grade":"四年级上册",
     "content":[["横看成岭侧成峰"],["远近高低各不同"],["不识庐山真面目"],["只缘身在此山中"]],
     "pinyin":[["héng kàn chéng lǐng cè chéng fēng"],["yuǎn jìn gāo dī gè bù tóng"],["bù shí lú shān zhēn miàn mù"],["zhǐ yuán shēn zài cǐ shān zhōng"]],
     "annotation":"缘：因为。识：认识，看清。",
     "translation":"横看是山岭侧看是山峰，远近高低看都不一样。看不清庐山的真面目，只因为自己身在山中。"},
    {"id":17,"title":"游山西村","author":"陆游","dynasty":"宋","grade":"四年级上册",
     "content":[["莫笑农家腊酒浑"],["丰年留客足鸡豚"],["山重水复疑无路"],["柳暗花明又一村"]],
     "pinyin":[["mò xiào nóng jiā là jiǔ hún"],["fēng nián liú kè zú jī tún"],["shān chóng shuǐ fù yí wú lù"],["liǔ àn huā míng yòu yī cūn"]],
     "annotation":"腊酒：腊月酿的酒。豚：猪。",
     "translation":"不要笑话农家腊酒浑浊，丰收之年招待客人有足够的鸡和猪。山重水复好像没有路了，柳暗花明又出现了一个村子。"},
    {"id":18,"title":"黄鹤楼送孟浩然之广陵","author":"李白","dynasty":"唐","grade":"四年级上册",
     "content":[["故人西辞黄鹤楼"],["烟花三月下扬州"],["孤帆远影碧空尽"],["唯见长江天际流"]],
     "pinyin":[["gù rén xī cí huáng hè lóu"],["yān huā sān yuè xià yáng zhōu"],["gū fān yuǎn yǐng bì kōng jìn"],["wéi jiàn cháng jiāng tiān jì liú"]],
     "annotation":"之：去，往。故人：老朋友。唯：只。",
     "translation":"老朋友在黄鹤楼和我告别，在繁花似锦的三月去扬州。小船的帆影渐渐消失在蓝天的尽头，只看见长江水在天边奔流。"},
    {"id":19,"title":"送元二使安西","author":"王维","dynasty":"唐","grade":"四年级下册",
     "content":[["渭城朝雨浥轻尘"],["客舍青青柳色新"],["劝君更尽一杯酒"],["西出阳关无故人"]],
     "pinyin":[["wèi chéng zhāo yǔ yì qīng chén"],["kè shè qīng qīng liǔ sè xīn"],["quàn jūn gèng jìn yī bēi jiǔ"],["xī chū yáng guān wú gù rén"]],
     "annotation":"浥：湿润。阳关：在甘肃敦煌。",
     "translation":"渭城的朝雨湿润了尘土，客舍旁的柳树青翠欲滴。再喝一杯酒吧，往西出了阳关就再也没有老朋友了。"},
    {"id":20,"title":"独坐敬亭山","author":"李白","dynasty":"唐","grade":"四年级下册",
     "content":[["众鸟高飞尽"],["孤云独去闲"],["相看两不厌"],["只有敬亭山"]],
     "pinyin":[["zhòng niǎo gāo fēi jìn"],["gū yún dú qù xián"],["xiāng kàn liǎng bù yàn"],["zhǐ yǒu jìng tíng shān"]],
     "annotation":"敬亭山在安徽。闲：悠闲。厌：满足。",
     "translation":"鸟儿们都飞走了，连一片云也悠闲地飘走了。互相对看不厌烦的，只有这座敬亭山。"},
    # 继续添加更多诗词...
    {"id":21,"title":"小池","author":"杨万里","dynasty":"宋","grade":"一年级下册",
     "content":[["泉眼无声惜细流"],["树阴照水爱晴柔"],["小荷才露尖尖角"],["早有蜻蜓立上头"]],
     "pinyin":[["quán yǎn wú shēng xī xì liú"],["shù yīn zhào shuǐ ài qíng róu"],["xiǎo hé cái lù jiān jiān jiǎo"],["zǎo yǒu qīng tíng lì shàng tóu"]],
     "annotation":"惜：爱惜。晴柔：晴天柔和的风光。",
     "translation":"泉水无声地细细流淌，树荫映在水面上，喜爱这晴日的柔和。小荷叶刚刚露出尖尖的角，早就有蜻蜓停在上头了。"},
    {"id":22,"title":"村居","author":"高鼎","dynasty":"清","grade":"二年级下册",
     "content":[["草长莺飞二月天"],["拂堤杨柳醉春烟"],["儿童散学归来早"],["忙趁东风放纸鸢"]],
     "pinyin":[["cǎo zhǎng yīng fēi èr yuè tiān"],["fú dī yáng liǔ zuì chūn yān"],["ér tóng sàn xué guī lái zǎo"],["máng chèn dōng fēng fàng zhǐ yuān"]],
     "annotation":"纸鸢：风筝。散学：放学。",
     "translation":"二月小草生长黄莺飞舞，杨柳拂堤沉醉在春烟里。孩子们放学早早回来，趁东风忙着放风筝。"},
    {"id":23,"title":"所见","author":"袁枚","dynasty":"清","grade":"二年级上册",
     "content":[["牧童骑黄牛"],["歌声振林樾"],["意欲捕鸣蝉"],["忽然闭口立"]],
     "pinyin":[["mù tóng qí huáng niú"],["gē shēng zhèn lín yuè"],["yì yù bǔ míng chán"],["hū rán bì kǒu lì"]],
     "annotation":"牧童：放牛的孩子。樾：树荫。意欲：想要。",
     "translation":"放牛娃骑着黄牛，歌声在树林中回荡。忽然想捉正在叫的知了，马上闭口站住不唱了。"},
    {"id":24,"title":"绝句","author":"杜甫","dynasty":"唐","grade":"三年级下册",
     "content":[["两个黄鹂鸣翠柳"],["一行白鹭上青天"],["窗含西岭千秋雪"],["门泊东吴万里船"]],
     "pinyin":[["liǎng gè huáng lí míng cuì liǔ"],["yī háng bái lù shàng qīng tiān"],["chuāng hán xī lǐng qiān qiū xuě"],["mén bó dōng wú wàn lǐ chuán"]],
     "annotation":"黄鹂：黄莺。千秋雪：千年不化的雪。",
     "translation":"两只黄莺在翠绿的柳树上唱歌，一行白鹭飞上了蓝天。窗外是西岭上的千年积雪，门前停着去东吴的万里航船。"},
    {"id":25,"title":"江雪","author":"柳宗元","dynasty":"唐","grade":"四年级下册",
     "content":[["千山鸟飞绝"],["万径人踪灭"],["孤舟蓑笠翁"],["独钓寒江雪"]],
     "pinyin":[["qiān shān niǎo fēi jué"],["wàn jìng rén zōng miè"],["gū zhōu suō lì wēng"],["dú diào hán jiāng xuě"]],
     "annotation":"绝：绝迹。蓑笠翁：披着蓑衣戴着斗笠的老人。",
     "translation":"所有的山都看不见鸟的影子，所有的路上都没有人的踪迹。只有一条小船上有个披蓑戴笠的老人，独自在下雪的江上垂钓。"},
]

# 继续扩充到75首
more_poems = [
    {"id":26,"title":"游子吟","author":"孟郊","dynasty":"唐","grade":"三年级下册",
     "content":[["慈母手中线"],["游子身上衣"],["临行密密缝"],["意恐迟迟归"],["谁言寸草心"],["报得三春晖"]],
     "pinyin":[["cí mǔ shǒu zhōng xiàn"],["yóu zǐ shēn shàng yī"],["lín xíng mì mì féng"],["yì kǒng chí chí guī"],["shuí yán cùn cǎo xīn"],["bào dé sān chūn huī"]],
     "annotation":"游子：离家远游的人。寸草心：比喻子女的心。三春晖：春天的阳光，比喻母爱。",
     "translation":"慈祥的母亲手中的针线，是为远行的儿子缝衣服。临走前密密地缝着，担心儿子迟迟不归。谁说小草的心，能报答得了春天的阳光呢？"},
    {"id":27,"title":"古朗月行","author":"李白","dynasty":"唐","grade":"一年级上册",
     "content":[["小时不识月"],["呼作白玉盘"],["又疑瑶台镜"],["飞在青云端"]],
     "pinyin":[["xiǎo shí bù shí yuè"],["hū zuò bái yù pán"],["yòu yí yáo tái jìng"],["fēi zài qīng yún duān"]],
     "annotation":"瑶台：传说中神仙住的地方。",
     "translation":"小时候不认识月亮，把它叫做白玉盘。又怀疑是瑶台的镜子，飞到了青云上面。"},
    {"id":28,"title":"江南","author":"汉乐府","dynasty":"汉","grade":"一年级上册",
     "content":[["江南可采莲"],["莲叶何田田"],["鱼戏莲叶间"],["鱼戏莲叶东"],["鱼戏莲叶西"],["鱼戏莲叶南"],["鱼戏莲叶北"]],
     "pinyin":[["jiāng nán kě cǎi lián"],["lián yè hé tián tián"],["yú xì lián yè jiān"],["yú xì lián yè dōng"],["yú xì lián yè xī"],["yú xì lián yè nán"],["yú xì lián yè běi"]],
     "annotation":"可：适宜。田田：莲叶茂密的样子。",
     "translation":"江南正是采莲的季节，莲叶多么茂盛啊。鱼儿在莲叶间嬉戏，一会儿游到东边，一会儿游到西边，一会儿游到南边，一会儿游到北边。"},
    {"id":29,"title":"敕勒歌","author":"北朝民歌","dynasty":"南北朝","grade":"二年级上册",
     "content":[["敕勒川，阴山下"],["天似穹庐，笼盖四野"],["天苍苍，野茫茫"],["风吹草低见牛羊"]],
     "pinyin":[["chì lè chuān，yīn shān xià"],["tiān sì qióng lú，lǒng gài sì yě"],["tiān cāng cāng，yě máng máng"],["fēng chuī cǎo dī jiàn niú yáng"]],
     "annotation":"穹庐：圆顶帐篷。见：通现，显露。",
     "translation":"敕勒川，在阴山脚下。天空像圆顶的帐篷，笼罩着四野。天蓝蓝的，草原茫茫无际。风吹过来，草低了，露出了牛羊。"},
    {"id":30,"title":"咏柳","author":"贺知章","dynasty":"唐","grade":"三年级下册",
     "content":[["碧玉妆成一树高"],["万条垂下绿丝绦"],["不知细叶谁裁出"],["二月春风似剪刀"]],
     "pinyin":[["bì yù zhuāng chéng yī shù gāo"],["wàn tiáo chuí xià lǜ sī tāo"],["bù zhī xì yè shuí cái chū"],["èr yuè chūn fēng sì jiǎn dāo"]],
     "annotation":"碧玉：绿色的玉。丝绦：丝带。",
     "translation":"高高的柳树像用碧玉装扮而成，万千柳条像绿色的丝带垂下来。不知道这细细的柳叶是谁剪出来的，二月的春风就像一把剪刀。"},
    {"id":31,"title":"回乡偶书","author":"贺知章","dynasty":"唐","grade":"四年级上册",
     "content":[["少小离家老大回"],["乡音无改鬓毛衰"],["儿童相见不相识"],["笑问客从何处来"]],
     "pinyin":[["shào xiǎo lí jiā lǎo dà huí"],["xiāng yīn wú gǎi bìn máo shuāi"],["ér tóng xiāng jiàn bù xiāng shí"],["xiào wèn kè cóng hé chù lái"]],
     "annotation":"偶书：偶然写的。衰：减少，变白。",
     "translation":"小时候离开家，老了才回来。家乡的口音没改，但头发已经白了。孩子们见了我都不认识，笑着问客人从哪里来。"},
    {"id":32,"title":"凉州词","author":"王之涣","dynasty":"唐","grade":"四年级上册",
     "content":[["黄河远上白云间"],["一片孤城万仞山"],["羌笛何须怨杨柳"],["春风不度玉门关"]],
     "pinyin":[["huáng hé yuǎn shàng bái yún jiān"],["yī piàn gū chéng wàn rèn shān"],["qiāng dí hé xū yuàn yáng liǔ"],["chūn fēng bù dù yù mén guān"]],
     "annotation":"仞：古代长度单位。羌笛：一种乐器。",
     "translation":"黄河远远地向上延伸到白云之间，一座孤城周围是万丈高山。羌笛何必吹着哀怨的杨柳曲，春风是吹不到玉门关外的。"},
    {"id":33,"title":"出塞","author":"王昌龄","dynasty":"唐","grade":"四年级下册",
     "content":[["秦时明月汉时关"],["万里长征人未还"],["但使龙城飞将在"],["不教胡马度阴山"]],
     "pinyin":[["qín shí míng yuè hàn shí guān"],["wàn lǐ cháng zhēng rén wèi huán"],["dàn shǐ lóng chéng fēi jiàng zài"],["bù jiào hú mǎ dù yīn shān"]],
     "annotation":"飞将：指飞将军李广。度：越过。",
     "translation":"明月还是秦时的明月，边关还是汉时的边关。万里出征的人还没回来。要是有飞将军李广在，决不让敌军越过阴山。"},
    {"id":34,"title":"芙蓉楼送辛渐","author":"王昌龄","dynasty":"唐","grade":"五年级上册",
     "content":[["寒雨连江夜入吴"],["平明送客楚山孤"],["洛阳亲友如相问"],["一片冰心在玉壶"]],
     "pinyin":[["hán yǔ lián jiāng yè rù wú"],["píng míng sòng kè chǔ shān gū"],["luò yáng qīn yǒu rú xiāng wèn"],["yī piàn bīng xīn zài yù hú"]],
     "annotation":"冰心：比喻心地纯洁。",
     "translation":"寒雨和江水连夜来到吴地，天亮时送别客人，楚山孤孤单单的。洛阳的亲友如果问起我，就说我一片冰心像放在玉壶里一样清白。"},
    {"id":35,"title":"鹿柴","author":"王维","dynasty":"唐","grade":"三年级上册",
     "content":[["空山不见人"],["但闻人语响"],["返景入深林"],["复照青苔上"]],
     "pinyin":[["kōng shān bù jiàn rén"],["dàn wén rén yǔ xiǎng"],["fǎn jǐng rù shēn lín"],["fù zhào qīng tái shàng"]],
     "annotation":"鹿柴：地名。但：只。返景：夕阳反照的光。",
     "translation":"空荡荡的山里看不见人，只听到有人说话的声音。夕阳的光芒照进深林，又照在青苔上面。"},
    {"id":36,"title":"早发白帝城","author":"李白","dynasty":"唐","grade":"三年级上册",
     "content":[["朝辞白帝彩云间"],["千里江陵一日还"],["两岸猿声啼不住"],["轻舟已过万重山"]],
     "pinyin":[["zhāo cí bái dì cǎi yún jiān"],["qiān lǐ jiāng líng yī rì huán"],["liǎng àn yuán shēng tí bù zhù"],["qīng zhōu yǐ guò wàn chóng shān"]],
     "annotation":"辞：告别。啼不住：叫声不停。",
     "translation":"早晨告别了彩云缭绕的白帝城，千里之外的江陵一天就能到。两岸猿猴的叫声还没停，小船已经穿过了万重山。"},
    {"id":37,"title":"枫桥夜泊","author":"张继","dynasty":"唐","grade":"五年级上册",
     "content":[["月落乌啼霜满天"],["江枫渔火对愁眠"],["姑苏城外寒山寺"],["夜半钟声到客船"]],
     "pinyin":[["yuè luò wū tí shuāng mǎn tiān"],["jiāng fēng yú huǒ duì chóu mián"],["gū sū chéng wài hán shān sì"],["yè bàn zhōng shēng dào kè chuán"]],
     "annotation":"乌啼：乌鸦叫。姑苏：苏州。",
     "translation":"月亮落下乌鸦啼叫寒霜满天，江边的枫树和渔火陪着忧愁的我入睡。姑苏城外寒山寺里，半夜的钟声传到了客船上。"},
    {"id":38,"title":"渔歌子","author":"张志和","dynasty":"唐","grade":"四年级下册",
     "content":[["西塞山前白鹭飞"],["桃花流水鳜鱼肥"],["青箬笠，绿蓑衣"],["斜风细雨不须归"]],
     "pinyin":[["xī sài shān qián bái lù fēi"],["táo huā liú shuǐ guì yú féi"],["qīng ruò lì，lǜ suō yī"],["xié fēng xì yǔ bù xū guī"]],
     "annotation":"鳜鱼：一种美味的鱼。箬笠：竹叶做的斗笠。",
     "translation":"西塞山前白鹭在飞，桃花盛开江水上涨鳜鱼正肥。戴着青斗笠，披着绿蓑衣，斜风细雨也不用回家。"},
    {"id":39,"title":"塞下曲","author":"卢纶","dynasty":"唐","grade":"六年级上册",
     "content":[["月黑雁飞高"],["单于夜遁逃"],["欲将轻骑逐"],["大雪满弓刀"]],
     "pinyin":[["yuè hēi yàn fēi gāo"],["chán yú yè dùn táo"],["yù jiāng qīng qí zhú"],["dà xuě mǎn gōng dāo"]],
     "annotation":"单于：匈奴首领。遁逃：逃跑。",
     "translation":"漆黑的夜里大雁高飞，敌军首领趁夜逃跑。正要派轻骑兵去追击，大雪落满了弓箭和刀。"},
    {"id":40,"title":"望洞庭","author":"刘禹锡","dynasty":"唐","grade":"四年级下册",
     "content":[["湖光秋月两相和"],["潭面无风镜未磨"],["遥望洞庭山水翠"],["白银盘里一青螺"]],
     "pinyin":[["hú guāng qiū yuè liǎng xiāng hé"],["tán miàn wú fēng jìng wèi mó"],["yáo wàng dòng tíng shān shuǐ cuì"],["bái yín pán lǐ yī qīng luó"]],
     "annotation":"和：和谐。潭面：湖面。青螺：青色的螺，比喻山。",
     "translation":"湖光和秋月相互映衬，湖面没有风像没磨过的镜子。远远望去洞庭山水一片翠绿，就像白银盘里放着一颗青螺。"},
    {"id":41,"title":"浪淘沙","author":"刘禹锡","dynasty":"唐","grade":"五年级上册",
     "content":[["九曲黄河万里沙"],["浪淘风簸自天涯"],["如今直上银河去"],["同到牵牛织女家"]],
     "pinyin":[["jiǔ qū huáng hé wàn lǐ shā"],["làng táo fēng bǒ zì tiān yá"],["rú jīn zhí shàng yín hé qù"],["tóng dào qiān niú zhī nǚ jiā"]],
     "annotation":"九曲：弯弯曲曲。簸：颠簸。",
     "translation":"弯弯曲曲的黄河挟带着万里黄沙，风浪颠簸来自天边。如今我要沿着黄河直到银河，一起到牵牛织女的家。"},
    {"id":42,"title":"赋得古原草送别","author":"白居易","dynasty":"唐","grade":"六年级上册",
     "content":[["离离原上草"],["一岁一枯荣"],["野火烧不尽"],["春风吹又生"],["远芳侵古道"],["晴翠接荒城"],["又送王孙去"],["萋萋满别情"]],
     "pinyin":[["lí lí yuán shàng cǎo"],["yī suì yī kū róng"],["yě huǒ shāo bù jìn"],["chūn fēng chuī yòu shēng"],["yuǎn fāng qīn gǔ dào"],["qíng cuì jiē huāng chéng"],["yòu sòng wáng sūn qù"],["qī qī mǎn bié qíng"]],
     "annotation":"离离：茂盛。远芳：远方的花草。王孙：贵族子弟，指朋友。",
     "translation":"原野上茂盛的草，一年一次枯萎又繁荣。野火烧不完，春风一吹又生长。远方的花香弥漫古道，晴空下绿色连接着荒城。又来送别朋友远去，茂盛的草都饱含离别之情。"},
    {"id":43,"title":"池上","author":"白居易","dynasty":"唐","grade":"一年级下册",
     "content":[["小娃撑小艇"],["偷采白莲回"],["不解藏踪迹"],["浮萍一道开"]],
     "pinyin":[["xiǎo wá chēng xiǎo tǐng"],["tōu cǎi bái lián huí"],["bù jiě cáng zōng jì"],["fú píng yī dào kāi"]],
     "annotation":"艇：小船。解：懂得。",
     "translation":"小娃娃撑着小船，偷偷去采了白莲花回来。不懂得隐藏自己的踪迹，浮萍被小船划开了一道水路。"},
    {"id":44,"title":"忆江南","author":"白居易","dynasty":"唐","grade":"四年级下册",
     "content":[["江南好，风景旧曾谙"],["日出江花红胜火"],["春来江水绿如蓝"],["能不忆江南？"]],
     "pinyin":[["jiāng nán hǎo，fēng jǐng jiù céng ān"],["rì chū jiāng huā hóng shèng huǒ"],["chūn lái jiāng shuǐ lǜ rú lán"],["néng bù yì jiāng nán？"]],
     "annotation":"谙：熟悉。蓝：蓝草，可做染料。",
     "translation":"江南真好啊，那风景以前就熟悉。太阳出来江边的花比火还红，春天来了江水绿得像蓝草。怎能不怀念江南呢？"},
    {"id":45,"title":"小儿垂钓","author":"胡令能","dynasty":"唐","grade":"三年级上册",
     "content":[["蓬头稚子学垂纶"],["侧坐莓苔草映身"],["路人借问遥招手"],["怕得鱼惊不应人"]],
     "pinyin":[["péng tóu zhì zǐ xué chuí lún"],["cè zuò méi tái cǎo yìng shēn"],["lù rén jiè wèn yáo zhāo shǒu"],["pà dé yú jīng bù yìng rén"]],
     "annotation":"垂纶：钓鱼。借问：问路。",
     "translation":"头发蓬乱的小孩在学钓鱼，侧身坐在青苔上，草遮住了身子。路人想问路，他远远地摆手，怕吓到鱼不肯回答。"},
    {"id":46,"title":"寻隐者不遇","author":"贾岛","dynasty":"唐","grade":"五年级上册",
     "content":[["松下问童子"],["言师采药去"],["只在此山中"],["云深不知处"]],
     "pinyin":[["sōng xià wèn tóng zǐ"],["yán shī cǎi yào qù"],["zhǐ zài cǐ shān zhōng"],["yún shēn bù zhī chù"]],
     "annotation":"隐者：隐居的人。言：说。",
     "translation":"在松树下问小童子，他说师父采药去了。只知道在这座山里，云雾很深不知道在哪里。"},
    {"id":47,"title":"山行","author":"杜牧","dynasty":"唐","grade":"三年级上册",
     "content":[["远上寒山石径斜"],["白云生处有人家"],["停车坐爱枫林晚"],["霜叶红于二月花"]],
     "pinyin":[["yuǎn shàng hán shān shí jìng xiá"],["bái yún shēng chù yǒu rén jiā"],["tíng chē zuò ài fēng lín wǎn"],["shuāng yè hóng yú èr yuè huā"]],
     "annotation":"径：小路。坐：因为。",
     "translation":"远远地走上寒山，石径弯弯斜斜。白云升起的地方有人家。停下车是因为喜爱傍晚的枫林，经霜的枫叶比二月的花还红。"},
    {"id":48,"title":"清明","author":"杜牧","dynasty":"唐","grade":"三年级下册",
     "content":[["清明时节雨纷纷"],["路上行人欲断魂"],["借问酒家何处有"],["牧童遥指杏花村"]],
     "pinyin":[["qīng míng shí jié yǔ fēn fēn"],["lù shàng xíng rén yù duàn hún"],["jiè wèn jiǔ jiā hé chù yǒu"],["mù tóng yáo zhǐ xìng huā cūn"]],
     "annotation":"断魂：形容非常伤心。借问：请问。",
     "translation":"清明时节细雨纷纷，路上的行人心情十分悲伤。请问哪里有酒店啊？牧童远远地指向杏花村。"},
    {"id":49,"title":"江南春","author":"杜牧","dynasty":"唐","grade":"六年级上册",
     "content":[["千里莺啼绿映红"],["水村山郭酒旗风"],["南朝四百八十寺"],["多少楼台烟雨中"]],
     "pinyin":[["qiān lǐ yīng tí lǜ yìng hóng"],["shuǐ cūn shān guō jiǔ qí fēng"],["nán cháo sì bǎi bā shí sì"],["duō shǎo lóu tái yān yǔ zhōng"]],
     "annotation":"山郭：山城。酒旗：酒店的旗子。",
     "translation":"千里江南黄莺啼叫绿树映红花，水边的村庄和山城酒旗在风中飘扬。南朝建了四百八十座寺庙，多少楼台都笼罩在烟雨之中。"},
    {"id":50,"title":"乐游原","author":"李商隐","dynasty":"唐","grade":"五年级下册",
     "content":[["向晚意不适"],["驱车登古原"],["夕阳无限好"],["只是近黄昏"]],
     "pinyin":[["xiàng wǎn yì bù shì"],["qū chē dēng gǔ yuán"],["xī yáng wú xiàn hǎo"],["zhǐ shì jìn huáng hūn"]],
     "annotation":"向晚：傍晚。意不适：心情不好。",
     "translation":"傍晚心情不太好，赶着车登上了乐游原。夕阳真是无限美好啊，只是已经接近黄昏了。"},
    {"id":51,"title":"蜂","author":"罗隐","dynasty":"唐","grade":"四年级上册",
     "content":[["不论平地与山尖"],["无限风光尽被占"],["采得百花成蜜后"],["为谁辛苦为谁甜"]],
     "pinyin":[["bù lùn píng dì yǔ shān jiān"],["wú xiàn fēng guāng jìn bèi zhàn"],["cǎi dé bǎi huā chéng mì hòu"],["wèi shuí xīn kǔ wèi shuí tián"]],
     "annotation":"不论：不管。尽被占：都被占领。",
     "translation":"不管是平地还是山顶，无限风光都被蜜蜂占据了。采了百花酿成蜜后，到底是为谁辛苦为谁甜呢？"},
    {"id":52,"title":"江上渔者","author":"范仲淹","dynasty":"宋","grade":"六年级上册",
     "content":[["江上往来人"],["但爱鲈鱼美"],["君看一叶舟"],["出没风波里"]],
     "pinyin":[["jiāng shàng wǎng lái rén"],["dàn ài lú yú měi"],["jūn kàn yī yè zhōu"],["chū mò fēng bō lǐ"]],
     "annotation":"但：只。君：你。出没：忽隐忽现。",
     "translation":"江上来来往往的人，只喜爱鲈鱼味道鲜美。你看那一叶小船，在风浪中忽隐忽现。"},
    {"id":53,"title":"泊船瓜洲","author":"王安石","dynasty":"宋","grade":"五年级上册",
     "content":[["京口瓜洲一水间"],["钟山只隔数重山"],["春风又绿江南岸"],["明月何时照我还"]],
     "pinyin":[["jīng kǒu guā zhōu yī shuǐ jiān"],["zhōng shān zhǐ gé shù chóng shān"],["chūn fēng yòu lǜ jiāng nán àn"],["míng yuè hé shí zhào wǒ huán"]],
     "annotation":"瓜洲：在江苏。绿：吹绿。",
     "translation":"京口和瓜洲只隔了一条江，钟山只隔了几重山。春风又一次吹绿了江南岸，明月什么时候能照我回家呢？"},
    {"id":54,"title":"书湖阴先生壁","author":"王安石","dynasty":"宋","grade":"六年级上册",
     "content":[["茅檐长扫净无苔"],["花木成畦手自栽"],["一水护田将绿绕"],["两山排闼送青来"]],
     "pinyin":[["máo yán cháng sǎo jìng wú tái"],["huā mù chéng qí shǒu zì zāi"],["yī shuǐ hù tián jiāng lǜ rào"],["liǎng shān pái tà sòng qīng lái"]],
     "annotation":"畦：菜园里划分的小块地。排闼：推开门。",
     "translation":"茅屋檐下经常打扫干净没有青苔，花草树木成行成块都是亲手种的。一条小河绕着绿色的田地，两座山推开门把青色送了进来。"},
    {"id":55,"title":"六月二十七日望湖楼醉书","author":"苏轼","dynasty":"宋","grade":"六年级上册",
     "content":[["黑云翻墨未遮山"],["白雨跳珠乱入船"],["卷地风来忽吹散"],["望湖楼下水如天"]],
     "pinyin":[["hēi yún fān mò wèi zhē shān"],["bái yǔ tiào zhū luàn rù chuán"],["juǎn dì fēng lái hū chuī sàn"],["wàng hú lóu xià shuǐ rú tiān"]],
     "annotation":"跳珠：跳动的珍珠。",
     "translation":"黑云像打翻的墨汁还没遮住山，白色的雨点像珍珠乱跳进船舱。卷地而来的风忽然把云吹散了，望湖楼下的水像天空一样明净。"},
    {"id":56,"title":"惠崇春江晚景","author":"苏轼","dynasty":"宋","grade":"三年级下册",
     "content":[["竹外桃花三两枝"],["春江水暖鸭先知"],["蒌蒿满地芦芽短"],["正是河豚欲上时"]],
     "pinyin":[["zhú wài táo huā sān liǎng zhī"],["chūn jiāng shuǐ nuǎn yā xiān zhī"],["lóu hāo mǎn dì lú yá duǎn"],["zhèng shì hé tún yù shàng shí"]],
     "annotation":"蒌蒿：一种野菜。河豚：一种鱼。",
     "translation":"竹林外桃花开了两三枝，春江水暖鸭子最先知道。蒌蒿满地芦芽还很短，正是河豚要游上来的时候。"},
    {"id":57,"title":"题临安邸","author":"林升","dynasty":"宋","grade":"五年级上册",
     "content":[["山外青山楼外楼"],["西湖歌舞几时休"],["暖风熏得游人醉"],["直把杭州作汴州"]],
     "pinyin":[["shān wài qīng shān lóu wài lóu"],["xī hú gē wǔ jǐ shí xiū"],["nuǎn fēng xūn dé yóu rén zuì"],["zhí bǎ háng zhōu zuò biàn zhōu"]],
     "annotation":"休：停止。熏：吹拂。汴州：北宋都城开封。",
     "translation":"山外有青山楼外有楼，西湖的歌舞什么时候才能停止？暖风把游人吹得醉醺醺的，简直把杭州当成了汴州。"},
    {"id":58,"title":"游园不值","author":"叶绍翁","dynasty":"宋","grade":"六年级下册",
     "content":[["应怜屐齿印苍苔"],["小扣柴扉久不开"],["春色满园关不住"],["一枝红杏出墙来"]],
     "pinyin":[["yīng lián jī chǐ yìn cāng tái"],["xiǎo kòu chái fēi jiǔ bù kāi"],["chūn sè mǎn yuán guān bù zhù"],["yī zhī hóng xìng chū qiáng lái"]],
     "annotation":"不值：没遇到主人。屐齿：木鞋的齿。",
     "translation":"大概是怕木屐踩坏了青苔，轻轻敲门很久也没人开。可是满园的春色是关不住的，一枝红杏花已经伸出了墙外。"},
    {"id":59,"title":"墨梅","author":"王冕","dynasty":"元","grade":"四年级下册",
     "content":[["吾家洗砚池头树"],["朵朵花开淡墨痕"],["不要人夸好颜色"],["只留清气满乾坤"]],
     "pinyin":[["wú jiā xǐ yàn chí tóu shù"],["duǒ duǒ huā kāi dàn mò hén"],["bù yào rén kuā hǎo yán sè"],["zhǐ liú qīng qì mǎn qián kūn"]],
     "annotation":"乾坤：天地。",
     "translation":"我家洗砚池边的梅树，每朵花开都带着淡淡的墨痕。不需要别人夸颜色好看，只愿清香充满天地之间。"},
    {"id":60,"title":"石灰吟","author":"于谦","dynasty":"明","grade":"六年级下册",
     "content":[["千锤万凿出深山"],["烈火焚烧若等闲"],["粉骨碎身浑不怕"],["要留清白在人间"]],
     "pinyin":[["qiān chuí wàn záo chū shēn shān"],["liè huǒ fén shāo ruò děng xián"],["fěn gǔ suì shēn hún bù pà"],["yào liú qīng bái zài rén jiān"]],
     "annotation":"千锤万凿：无数次的锤打和开凿。浑：全。",
     "translation":"经过千锤万凿从深山里出来，烈火烧身也视若等闲。粉身碎骨全都不怕，要把一身清白留在人间。"},
    {"id":61,"title":"竹石","author":"郑燮","dynasty":"清","grade":"六年级下册",
     "content":[["咬定青山不放松"],["立根原在破岩中"],["千磨万击还坚劲"],["任尔东西南北风"]],
     "pinyin":[["yǎo dìng qīng shān bù fàng sōng"],["lì gēn yuán zài pò yán zhōng"],["qiān mó wàn jī hái jiān jìng"],["rèn ěr dōng xī nán běi fēng"]],
     "annotation":"咬定：紧紧抓住。任尔：不管你。",
     "translation":"紧紧咬住青山绝不放松，根扎在破裂的岩石中。经历无数磨难还是那样坚韧，不管你刮什么方向的狂风。"},
    {"id":62,"title":"村晚","author":"雷震","dynasty":"宋","grade":"五年级下册",
     "content":[["草满池塘水满陂"],["山衔落日浸寒漪"],["牧童归去横牛背"],["短笛无腔信口吹"]],
     "pinyin":[["cǎo mǎn chí táng shuǐ mǎn bēi"],["shān xián luò rì jìn hán yī"],["mù tóng guī qù héng niú bèi"],["duǎn dí wú qiāng xìn kǒu chuī"]],
     "annotation":"陂：池塘。漪：水波。腔：曲调。",
     "translation":"池塘边长满青草，池水快要溢出。远山衔着落日倒映在清凉的水波中。放牛的孩子横坐在牛背上回家，短笛随便吹着不成曲调的歌。"},
    {"id":63,"title":"四时田园杂兴","author":"范成大","dynasty":"宋","grade":"四年级下册",
     "content":[["昼出耘田夜绩麻"],["村庄儿女各当家"],["童孙未解供耕织"],["也傍桑阴学种瓜"]],
     "pinyin":[["zhòu chū yún tián yè jì má"],["cūn zhuāng ér nǚ gè dāng jiā"],["tóng sūn wèi jiě gōng gēng zhī"],["yě bàng sāng yīn xué zhǒng guā"]],
     "annotation":"绩麻：搓麻绳。供：从事。",
     "translation":"白天去田里除草，晚上搓麻绳。村子里的男男女女都各忙各的。小孙子还不懂耕田织布，也在桑树荫下学着种瓜。"},
    {"id":64,"title":"稚子弄冰","author":"杨万里","dynasty":"宋","grade":"五年级下册",
     "content":[["稚子金盆脱晓冰"],["彩丝穿取当银钲"],["敲成玉磬穿林响"],["忽作玻璃碎地声"]],
     "pinyin":[["zhì zǐ jīn pén tuō xiǎo bīng"],["cǎi sī chuān qǔ dāng yín zhēng"],["qiāo chéng yù qìng chuān lín xiǎng"],["hū zuò bō lí suì dì shēng"]],
     "annotation":"稚子：小孩子。罄：古代一种打击乐器。",
     "translation":"小孩子把盆里的冰取出来，用彩线穿起来当银锣敲。敲出玉磬一样的声响穿过树林，忽然哗啦一声像玻璃碎了一地。"},
    {"id":65,"title":"三衢道中","author":"曾几","dynasty":"宋","grade":"三年级下册",
     "content":[["梅子黄时日日晴"],["小溪泛尽却山行"],["绿阴不减来时路"],["添得黄鹂四五声"]],
     "pinyin":[["méi zǐ huáng shí rì rì qíng"],["xiǎo xī fàn jìn què shān xíng"],["lǜ yīn bù jiǎn lái shí lù"],["tiān dé huáng lí sì wǔ shēng"]],
     "annotation":"三衢：地名。泛：乘船。",
     "translation":"梅子黄了的时节天天都是晴天，乘小船到了小溪尽头改走山路。路边的绿荫不比来的时候少，还多了黄鹂的几声啼叫。"},
    {"id":66,"title":"示儿","author":"陆游","dynasty":"宋","grade":"六年级上册",
     "content":[["死去元知万事空"],["但悲不见九州同"],["王师北定中原日"],["家祭无忘告乃翁"]],
     "pinyin":[["sǐ qù yuán zhī wàn shì kōng"],["dàn bēi bù jiàn jiǔ zhōu tóng"],["wáng shī běi dìng zhōng yuán rì"],["jiā jì wú wàng gào nǎi wēng"]],
     "annotation":"元知：原本知道。同：统一。乃翁：你的父亲。",
     "translation":"本来知道死后万事皆空，只是悲伤看不到国家统一。等到朝廷军队收复中原的那一天，家祭时别忘了告诉你父亲。"},
    {"id":67,"title":"秋夜将晓出篱门迎凉有感","author":"陆游","dynasty":"宋","grade":"五年级下册",
     "content":[["三万里河东入海"],["五千仞岳上摩天"],["遗民泪尽胡尘里"],["南望王师又一年"]],
     "pinyin":[["sān wàn lǐ hé dōng rù hǎi"],["wǔ qiān rèn yuè shàng mó tiān"],["yí mín lèi jìn hú chén lǐ"],["nán wàng wáng shī yòu yī nián"]],
     "annotation":"河：黄河。仞：古代长度单位。遗民：沦陷区的百姓。",
     "translation":"三万里的黄河东流入海，五千仞的高山直插云天。沦陷区的百姓在敌人的铁蹄下眼泪都流干了，向南盼望朝廷的军队又是一年。"},
    {"id":68,"title":"观书有感","author":"朱熹","dynasty":"宋","grade":"五年级上册",
     "content":[["半亩方塘一鉴开"],["天光云影共徘徊"],["问渠那得清如许"],["为有源头活水来"]],
     "pinyin":[["bàn mǔ fāng táng yī jiàn kāi"],["tiān guāng yún yǐng gòng pái huái"],["wèn qú nǎ dé qīng rú xǔ"],["wèi yǒu yuán tóu huó shuǐ lái"]],
     "annotation":"鉴：镜子。渠：它，指方塘。",
     "translation":"半亩大小的方塘像一面镜子打开，天光和云影一起在水中徘徊。要问它为什么这样清澈，因为源头有活水不断地流来。"},
    {"id":69,"title":"长相思","author":"纳兰性德","dynasty":"清","grade":"五年级上册",
     "content":[["山一程，水一程"],["身向榆关那畔行"],["夜深千帐灯"],["风一更，雪一更"],["聒碎乡心梦不成"],["故园无此声"]],
     "pinyin":[["shān yī chéng，shuǐ yī chéng"],["shēn xiàng yú guān nà pàn xíng"],["yè shēn qiān zhàng dēng"],["fēng yī gēng，xuě yī gēng"],["guō suì xiāng xīn mèng bù chéng"],["gù yuán wú cǐ shēng"]],
     "annotation":"榆关：山海关。聒：吵闹。",
     "translation":"走了一程山路又一程水路，向着山海关那边行进。深夜数千帐篷都亮着灯。刮了一更风又下一更雪，风雪声吵碎了思乡的心让人睡不着，家乡没有这种声音。"},
    {"id":70,"title":"己亥杂诗","author":"龚自珍","dynasty":"清","grade":"六年级下册",
     "content":[["九州生气恃风雷"],["万马齐喑究可哀"],["我劝天公重抖擞"],["不拘一格降人才"]],
     "pinyin":[["jiǔ zhōu shēng qì shì fēng léi"],["wàn mǎ qí yīn jiū kě āi"],["wǒ quàn tiān gōng chóng dǒu sǒu"],["bù jū yī gé jiàng rén cái"]],
     "annotation":"恃：依靠。喑：沉默。抖擞：振作。",
     "translation":"国家的生机要依靠风雷激荡，万马齐喑的局面实在可悲。我希望老天重新振作精神，不拘一格地降下各种人才。"},
    {"id":71,"title":"寒食","author":"韩翃","dynasty":"唐","grade":"六年级下册",
     "content":[["春城无处不飞花"],["寒食东风御柳斜"],["日暮汉宫传蜡烛"],["轻烟散入五侯家"]],
     "pinyin":[["chūn chéng wú chù bù fēi huā"],["hán shí dōng fēng yù liǔ xiá"],["rì mù hàn gōng chuán là zhú"],["qīng yān sàn rù wǔ hóu jiā"]],
     "annotation":"寒食：寒食节。五侯：泛指贵族。",
     "translation":"春天的长安城到处飞花，寒食节东风吹得宫中的柳树斜斜的。天黑时分宫里传递蜡烛，轻烟飘进了权贵之家。"},
    {"id":72,"title":"迢迢牵牛星","author":"佚名","dynasty":"汉","grade":"六年级下册",
     "content":[["迢迢牵牛星"],["皎皎河汉女"],["纤纤擢素手"],["札札弄机杼"],["终日不成章"],["泣涕零如雨"],["河汉清且浅"],["相去复几许"],["盈盈一水间"],["脉脉不得语"]],
     "pinyin":[["tiáo tiáo qiān niú xīng"],["jiǎo jiǎo hé hàn nǚ"],["xiān xiān zhuó sù shǒu"],["zhá zhá nòng jī zhù"],["zhōng rì bù chéng zhāng"],["qì tì líng rú yǔ"],["hé hàn qīng qiě qiǎn"],["xiāng qù fù jǐ xǔ"],["yíng yíng yī shuǐ jiān"],["mò mò bù dé yǔ"]],
     "annotation":"迢迢：遥远。皎皎：明亮。河汉：银河。擢：摆动。",
     "translation":"遥远的牵牛星，明亮的织女星。纤细的手摆弄着织布机，织布声札札作响。一整天织不成一段布，眼泪像雨一样落下。银河又清又浅，两人相距有多远呢？只是隔着一条清澈的河水，却只能含情脉脉地相望无法言语。"},
    {"id":73,"title":"长歌行","author":"汉乐府","dynasty":"汉","grade":"六年级下册",
     "content":[["青青园中葵"],["朝露待日晞"],["阳春布德泽"],["万物生光辉"],["常恐秋节至"],["焜黄华叶衰"],["百川东到海"],["何时复西归"],["少壮不努力"],["老大徒伤悲"]],
     "pinyin":[["qīng qīng yuán zhōng kuí"],["zhāo lù dài rì xī"],["yáng chūn bù dé zé"],["wàn wù shēng guāng huī"],["cháng kǒng qiū jié zhì"],["kūn huáng huā yè shuāi"],["bǎi chuān dōng dào hǎi"],["hé shí fù xī guī"],["shào zhuàng bù nǔ lì"],["lǎo dà tú shāng bēi"]],
     "annotation":"晞：晒干。焜黄：枯黄。徒：白白地。",
     "translation":"园中的葵菜青青翠翠，早晨的露水等待阳光晒干。春天把恩泽洒满大地，万物都闪耀着光辉。常常担心秋天到来，花叶枯黄衰败。百川东流入大海，什么时候能再往西流回来？年轻时不努力，到老了只能白白地后悔悲伤。"},
    {"id":74,"title":"十五夜望月","author":"王建","dynasty":"唐","grade":"六年级下册",
     "content":[["中庭地白树栖鸦"],["冷露无声湿桂花"],["今夜月明人尽望"],["不知秋思落谁家"]],
     "pinyin":[["zhōng tíng dì bái shù qī yā"],["lěng lù wú shēng shī guì huā"],["jīn yè yuè míng rén jìn wàng"],["bù zhī qiū sī luò shuí jiā"]],
     "annotation":"地白：月光照在地上。秋思：秋天的思念。",
     "translation":"庭院中月光照得地面发白，树上栖着乌鸦。冷冷的露水无声地打湿了桂花。今夜明月当空人人都在望月，不知道秋天的思念落到了谁家。"},
    {"id":75,"title":"马诗","author":"李贺","dynasty":"唐","grade":"六年级下册",
     "content":[["大漠沙如雪"],["燕山月似钩"],["何当金络脑"],["快走踏清秋"]],
     "pinyin":[["dà mò shā rú xuě"],["yān shān yuè sì gōu"],["hé dāng jīn luò nǎo"],["kuài zǒu tà qīng qiū"]],
     "annotation":"络脑：马笼头。何当：什么时候。",
     "translation":"大沙漠里的沙像雪一样白，燕山上的月亮像弯钩。什么时候能戴上金笼头，在清爽的秋天里飞快奔驰。"},
]

poems += more_poems

# 输出 JS
output_path = r"D:\WorkbuddyData\李昱泽学习\study-workbench\js\data\poetry.js"
with open(output_path, "w", encoding="utf-8") as f:
    f.write("// 小学必备古诗词 75首\n")
    f.write("const POETRY_DATA = ")
    json.dump(poems, f, ensure_ascii=False, indent=2)
    f.write(";\n")

print(f"Generated {len(poems)} poems")
